# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

# authenticate as a user for fallback
provider "google" {
  region                = "us-central1"
  billing_project       = "ahia-gcp-iam-b863"
  user_project_override = true
}
provider "google-beta" {
  region                = "us-central1"
  billing_project       = "ahia-gcp-iam-b863"
  user_project_override = true
}


