

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec: 
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.0.x
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  targetNamespace: observability
  interval: 1h