

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 10m
  url: oci://ghcr.io/prometheus-community/charts/ 
  type: oci